def reader_css():
    return (
        "img { max-width: 100% !important; height: auto !important; } "
        "body { overflow-wrap: anywhere; word-wrap: break-word; } "
        "pre, code { white-space: pre-wrap; } "
        "span[data-tts-idx] { transition: background-color 0.2s ease; } "
        "span[data-tts-idx].tts-highlight { background-color: #fff3cd; }"
    )


def build_reader_script(css=None):
    if css is None:
        css = reader_css()
    return (
        "(function() {"
        "  var style = document.getElementById('copilot-reader-style');"
        "  if (!style) {"
        "    style = document.createElement('style');"
        "    style.id = 'copilot-reader-style';"
        "    document.head.appendChild(style);"
        "  }"
        f"  style.textContent = {css!r};"
        "  window.setTtsHighlight = function(sentenceIdx) {"
        "    document.querySelectorAll('span[data-tts-idx].tts-highlight').forEach(el => {"
        "      el.classList.remove('tts-highlight');"
        "    });"
        "    if (sentenceIdx >= 0) {"
        "      var el = document.querySelector('span[data-tts-idx=\"' + sentenceIdx + '\"]');"
        "      if (el) {"
        "        console.log('Highlighting sentence', sentenceIdx);"
        "        el.classList.add('tts-highlight');"
        "        el.scrollIntoView({block: 'center', behavior: 'smooth'});"
        "      } else {"
        "        console.warn('Sentence span not found for index', sentenceIdx);"
        "      }"
        "    }"
        "  };"
        "  window.wrapSentences = function(sentences, charPositions) {"
        "    if (!sentences || sentences.length === 0) { console.log('wrapSentences: no sentences'); return; }"
        "    try {"
        "      console.log('wrapSentences called with', sentences.length, 'sentences');"
        "      var body = document.body;"
        "      var walker = document.createTreeWalker(body, NodeFilter.SHOW_TEXT, null, false);"
        "      var textNodes = [];"
        "      var node;"
        "      while (node = walker.nextNode()) {"
        "        if (node.nodeValue && node.nodeValue.trim()) textNodes.push(node);"
        "      }"
        "      console.log('Found', textNodes.length, 'text nodes');"
        "      var wrappedCount = 0;"
        "      var fullText = '';"
        "      for (var tn of textNodes) fullText += tn.nodeValue;"
        "      console.log('Full DOM text length:', fullText.length);"
        "      for (var s = 0; s < sentences.length; s++) {"
        "        var sentence = sentences[s].trim();"
        "        if (!sentence) continue;"
        "        var cleanedForSearch = sentence.replace(/\\s+/g, ' ').substring(0, 50);"
        "        var idx = fullText.indexOf(sentence);"
        "        if (idx < 0) idx = fullText.indexOf(cleanedForSearch);"
        "        if (idx >= 0) {"
        "          var sentenceLen = sentence.length;"
        "          var currentPos = 0;"
        "          for (var i = 0; i < textNodes.length; i++) {"
        "            var tn = textNodes[i];"
        "            var tnLen = tn.nodeValue.length;"
        "            if (currentPos + tnLen > idx && currentPos < idx + sentenceLen) {"
        "              var relStart = Math.max(0, idx - currentPos);"
        "              var relEnd = Math.min(tnLen, idx + sentenceLen - currentPos);"
        "              if (relStart < relEnd) {"
        "                var before = tn.nodeValue.substring(0, relStart);"
        "                var during = tn.nodeValue.substring(relStart, relEnd);"
        "                var after = tn.nodeValue.substring(relEnd);"
        "                var parent = tn.parentNode;"
        "                var span = document.createElement('span');"
        "                span.setAttribute('data-tts-idx', s);"
        "                span.textContent = during;"
        "                if (before) parent.insertBefore(document.createTextNode(before), tn);"
        "                parent.insertBefore(span, tn);"
        "                if (after) parent.insertBefore(document.createTextNode(after), tn);"
        "                parent.removeChild(tn);"
        "                wrappedCount++;"
        "                break;"
        "              }"
        "            }"
        "            currentPos += tnLen;"
        "          }"
        "          fullText = fullText.substring(0, idx) + ' '.repeat(sentenceLen) + fullText.substring(idx + sentenceLen);"
        "        }"
        "      }"
        "      console.log('Successfully wrapped', wrappedCount, 'sentences');"
        "    } catch (e) {"
        "      console.error('Error wrapping sentences:', e.message, e.stack);"
        "    }"
        "  };"
        "  window.consoleMessages = [];"
        "  var origLog = console.log;"
        "  var origWarn = console.warn;"
        "  var origError = console.error;"
        "  console.log = function() {"
        "    origLog.apply(console, arguments);"
        "    window.consoleMessages.push({level: 'LOG', text: Array.from(arguments).join(' ')});"
        "  };"
        "  console.warn = function() {"
        "    origWarn.apply(console, arguments);"
        "    window.consoleMessages.push({level: 'WARN', text: Array.from(arguments).join(' ')});"
        "  };"
        "  console.error = function() {"
        "    origError.apply(console, arguments);"
        "    window.consoleMessages.push({level: 'ERROR', text: Array.from(arguments).join(' ')});"
        "  };"
        "})();"
    )
